# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.0.6'

gem 'activeadmin'
gem 'autoprefixer-rails'
gem 'babel-transpiler'
gem 'binascii'
gem 'bootstrap-sass'
gem 'carrierwave'
gem 'coffee-rails'
gem 'devise'
gem 'elasticsearch', '< 7.14'
gem 'elasticsearch-model'
gem 'elasticsearch-persistence'
gem 'elasticsearch-rails'
gem 'figaro'
gem 'fog-aws'
gem 'font_awesome5_rails'
gem 'formtastic'
gem 'grape', '~> 1.7'
gem 'grape-entity'
gem 'grape_on_rails_routes'
gem 'grape-papertrail', '~> 0.2.0'
gem 'httparty'
gem 'invisible_captcha'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
# for api pagination
gem 'kaminari'
gem 'kramdown'
gem 'mini_racer'
gem 'paper_trail'
gem 'pg', '~> 0.21'
gem 'puma', '>= 3.12.4'
gem 'pundit'
gem 'rack-attack'
gem 'rack-cors'
gem 'rails', '~> 6.1'
gem 'ransack'
gem 'rb-readline'
gem 'redis'
# for tosback2:
gem 'sanitize'
gem 'sendgrid-ruby'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'simple_form'
gem 'uglifier'
gem 'uuid', '~> 2.3', '>= 2.3.9'
gem 'uuidtools', '~> 2.1', '>= 2.1.5'
gem 'vuejs-rails', '~> 2.3.2'
gem 'whenever'

group :development do
  gem 'get_process_mem'
  gem 'letter_opener'
  # for performance
  gem 'memory_profiler'
  gem 'web-console', '>= 3.3.0'
end

group :development, :test do
  gem 'active_record_query_trace'
  gem 'bullet'
  gem 'capybara'
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'flamegraph'
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pundit-matchers', '~> 1.6.0'
  gem 'rack-mini-profiler'
  gem 'rspec-rails', '~> 4.0.2'
  gem 'rubocop-rspec', require: false
  gem 'simplecov', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'stackprof'
  gem 'webmock'
end

gem "node-runner", "~> 1.1"
