# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.4.9'

gem 'base64'
gem 'bigdecimal'
gem 'csv'
gem 'drb'
gem 'mutex_m'
gem 'observer'
gem 'ostruct'
gem 'nkf'
gem 'activeadmin', '~> 3.5.0'
gem 'autoprefixer-rails'
gem 'babel-transpiler'
gem 'binascii'
gem 'bootstrap-sass'
gem 'carrierwave', '>= 2.2.6'
gem 'coffee-rails'
gem 'devise', '>= 4.9.4'
gem 'elasticsearch', '< 7.14'
gem 'elasticsearch-model'
gem 'elasticsearch-persistence'
gem 'elasticsearch-rails'
gem 'faraday', '~> 1.10', '>= 1.10.5'
gem 'figaro'
gem 'fog-aws'
gem 'font_awesome5_rails'
gem 'formtastic'
gem 'grape', '~> 1.7'
gem 'grape-entity'
gem 'grape_on_rails_routes'
gem 'grape-papertrail', '~> 0.2.0'
gem 'httparty', '>= 0.24.0'
gem 'invisible_captcha'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
# for api pagination
gem 'kaminari'
gem 'kramdown'
gem 'net-imap', '>= 0.5.7'
gem 'node-runner', '~> 1.1'
gem 'nokogiri', '>= 1.19.1'
gem 'paper_trail', '>= 15.0'
gem 'pg', '~> 1.5', '>= 1.5.9'
gem 'puma', '>= 6.4.3'
gem 'pundit'
gem 'rack', '>= 2.2.22'
gem 'rack-attack'
gem 'rack-cors', '>= 2.0.2'
gem 'rails', '~> 7.1.0', '>= 7.1.5.2'
gem 'ransack'
gem 'rb-readline'
gem 'redis'
gem 'rexml', '>= 3.3.9'
# for tosback2:
gem 'sanitize'
gem 'sassc-rails'
gem 'sendgrid-ruby'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'simple_form'
gem 'thor', '>= 1.4.0'
gem 'uglifier'
gem 'sprockets-rails'
gem 'uuid', '~> 2.3', '>= 2.3.9'
gem 'uuidtools', '~> 2.1', '>= 2.1.5'
gem 'vuejs-rails', '~> 2.3.2'
gem 'whenever'

group :development do
  gem 'get_process_mem'
  gem 'letter_opener'
  # for performance
  gem 'memory_profiler'
  gem 'web-console', '>= 3.3.0'
end

group :development, :test do
  gem 'active_record_query_trace'
  gem 'bullet', '>= 8.0'
  gem 'capybara'
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'flamegraph'
  gem 'listen', '~> 3.5'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pundit-matchers', '~> 1.6.0'
  gem 'rack-mini-profiler'
  gem 'rspec-rails', '~> 4.0.2'
  gem 'rubocop-rspec', require: false
  gem 'simplecov', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.1'
  gem 'stackprof'
  gem 'webmock'
end
