# PostgreSQL. Versions 9.1 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
#

development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { } %>
  username: <%= ENV.fetch("DATABASE_USER") { } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { } %>
  database: phoenix_development

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { } %>
  username: <%= ENV.fetch("DATABASE_USER") { } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { } %>
  database: phoenix_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { } %>
  username: <%= ENV.fetch("DATABASE_USER") { } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { } %>
  database: phoenix_production

staging:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { } %>
  username: <%= ENV.fetch("DATABASE_USER") { } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { } %>
  database: phoenix_staging

docker:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { } %>
  username: <%= ENV.fetch("DATABASE_USER") { } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { } %>
  database: postgres
